# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcac79f7d8d723e549383d8b7822836f4427c8bd895dd293afc8b459c171bb0efbd5797a5331291f28803ef1299ad6057053e2f717568bd4506104157059331d

test:
  secret_key_base: 958a2aeaff965ea84b1c466e4db7168424affb5be080844ff7d1189c241511cf04b4e535f3d454cd0f71cd2640636e84e19e1dfbdf1e3e8ac284d9010a2a9784

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
